### ISSUE TITLE
Can't install - runtime org.freedesktop.Platform/x86_64/21.08 not found

### ISSUE THREAD

**Issue by RDKRACZ** [flathub/com.brave.Browser#107]
This is really weird issue. Looks like something on flatpak side but they want me to report it here first
Brave requires org.freedesktop.Platform which is installed but brave doesn't detect it?
```
flatpak install flathub-beta com.brave.Browser
Looking for matches…
error: The application com.brave.Browser/x86_64/beta requires the runtime org.freedesktop.Platform/x86_64/21.08 which was not found
```
```
flatpak install org.freedesktop.Platform
Looking for matches…
Remotes found with refs similar to ‘org.freedesktop.Platform’:

   1) ‘flathub-beta’ (system)
   2) ‘flathub’ (user)

Which do you want to use (0 to abort)? [0-2]: 2
Similar refs found for ‘org.freedesktop.Platform’ in remote ‘flathub’ (user):

   1) runtime/org.freedesktop.Platform/x86_64/19.08
   2) runtime/org.freedesktop.Platform/x86_64/1.6
   3) runtime/org.freedesktop.Platform/x86_64/20.08
   4) runtime/org.freedesktop.Platform/x86_64/21.08
   5) runtime/org.freedesktop.Platform/x86_64/18.08

Which do you want to use (0 to abort)? [0-5]: 4
Skipping: org.freedesktop.Platform/x86_64/21.08 is already installed
```

**Comment by TheEvilSkeleton** [comment]
From the looks of it, your `flathub-beta` remote is added system-wide whereas the `flathub` remote is added for the user. You'll have to either add the `flathub` remote system-wide:

```
flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
```

or add the `flathub-beta` remote for the user:

```
flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
```

**Comment by RDKRACZ** [comment]
Thank you, this worked.

**Comment by 238Ver** [comment]
> From the looks of it, the `flathub-beta` remote is added system-wide whereas the `flathub` remote is added for the user only. You'll have to either add the `flathub`[a] remote system-wide **or** add the `flathub-beta` remote for the user[b] (whichever you prefer):
> 
> [a]
> 
> ```
> flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
> ```
> 
> [b]
> 
> ```
> flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
> ```
> 
> After that, try again and see if it works.

Thx a lot
