### ISSUE TITLE
GTK+ theme on wayland broken

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/com.brave.Browser#121]
It has these weird edges that flicker.

![image](https://user-images.githubusercontent.com/14835120/162721120-121220ee-bf62-4a86-b4c9-c0da913687e0.png)

**Comment by TheEvilSkeleton** [comment]
Is it reproducible in the non Flatpak version of Brave? I can't reproduce it on my end.

**Comment by alvarlagerlof** [comment]
It seems to be only on XWayland. I tried changing the Preferred Ozone platform to Wayland on Flatpak and the issue went away, but the text on the UI became unusably small. 

I also tried inside Toolbox and then the Preferred Ozone platform option was not available. Don't know what to make of that.

**Comment by alvarlagerlof** [comment]
It seems to be only on XWayland. I tried changing the Preferred Ozone platform to Wayland on Flatpak and the issue went away, but the text on the UI became unusably small. 

I also tried inside Toolbox and then the Preferred Ozone platform option was not available. Don't know what to make of that.
