### ISSUE TITLE
Dark theme doesn't work with GTK theme

### ISSUE THREAD

**Issue by franciscot** [flathub/com.brave.Browser#123]
Hi, I can't get dark theme to work with gtk in brave.

Dark theme with GTK:
![brave_gtk_dark_theme](https://user-images.githubusercontent.com/5504418/163668069-52507010-ad02-4c42-bf64-bb8a3b7aad8a.jpg)

and classic theme: 
![brave_classic_dark_theme](https://user-images.githubusercontent.com/5504418/163668098-7f8b74f3-08fe-4f65-819f-bd22af924680.jpg)

On Snap, GTK dark theme is working.
My desktop (plasma) is setting with dark aspect and theme, included gtk apps.

My system:
Operating System: KDE neon 5.24
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.3
Kernel Version: 5.13.0-39-generic (64-bit)
Graphics Platform: X11
Processors: 12 × Intel® Core™ i7-10750H CPU @ 2.60GHz
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1650/PCIe/SSE2

Thank you.

**Comment by TheEvilSkeleton** [comment]
Can you run `flatpak update` in the terminal? It should find `org.gtk.Gtk3theme.Adwaita-dark`. If not, what happens when you run `flatpak list | grep org.gtk.Gtk3theme.Adwaita-dark`?

**Comment by franciscot** [comment]
> Can you run `flatpak update` in the terminal? It should find `org.gtk.Gtk3theme.Adwaita-dark`. If not, what happens when you run `flatpak list | grep org.gtk.Gtk3theme.Adwaita-dark`?

`flatpak update` say nothing to do. It's updated.

`org.gtk.Gtk3theme.Adwaita-dark` is not installed.

I have intalled this:
```
Freedesktop SDK  org.freedesktop.Sdk  21.08.12  21.08  system
GNOME Application Platform version 42  org.gnome.Platform  42  system
Breeze GTK theme  org.gtk.Gtk3theme.Breeze  3.22   system
KDE Application Platform   org.kde.Platform  5.15-21.08   system
```
I intalled `org.gtk.Gtk3theme.Adwaita-dark` and `org.gtk.Gtk3theme.Breeze-Dark`, but nothing changes.

**Comment by BirdInFire** [comment]
> > Can you run `flatpak update` in the terminal? It should find `org.gtk.Gtk3theme.Adwaita-dark`. If not, what happens when you run `flatpak list | grep org.gtk.Gtk3theme.Adwaita-dark`?
> 
> `flatpak update` say nothing to do. It's updated.
> 
> `org.gtk.Gtk3theme.Adwaita-dark` is not installed.
> 
> I have intalled this:
> 
> ```
> Freedesktop SDK  org.freedesktop.Sdk  21.08.12  21.08  system
> GNOME Application Platform version 42  org.gnome.Platform  42  system
> Breeze GTK theme  org.gtk.Gtk3theme.Breeze  3.22   system
> KDE Application Platform   org.kde.Platform  5.15-21.08   system
> ```
> 
> I intalled `org.gtk.Gtk3theme.Adwaita-dark` and `org.gtk.Gtk3theme.Breeze-Dark`, but nothing changes.

you can try to check you theme name and install both version (dark and light) for instance i use (adw-gtk3) and i had to install on my (.local/share/theme) both version (dark and light) and on flatpak dark and light before it work.

fixed it for me so cost nothing to test.

**Comment by mahtjarohst** [comment]
I would like for someone to revisit this bug. The flatpak org.gtk.Gtk3theme.Breeze package works perfectly fine for Firefox flatpak, for both light and dark mode. Brave browser flatpak seems to not work this way. I have even set `flatpak override com.brave.Browser --env GTK_THEME=Breeze`, and it still will not use the dark mode. Are there any work arounds for this, or will the bug be addressed?

**Comment by rany2** [comment]
I can't reproduce this unfortunately. Both the classic and GTK theme work as expected and the dark theme works fine.

**Comment by mahtjarohst** [comment]
Info: runtime org.gtk.Gtk3theme.Breeze-Dark branch 3.22 is end-of-life, with reason:
   This theme has been replaced by org.gtk.Gtk3theme.Breeze, see README for workaround on using system color schemes. https://github.com/flathub/org.gtk.Gtk3theme.Breeze#workarounds

I was able to somewhat workaround it by setting

`flatpak override --user --filesystem=xdg-config/gtk-3.0:ro`

As you can see, the theme is applied, but doesn't look quite right.
Better than having it be light mode though.

![Screenshot_20230301_190739](https://user-images.githubusercontent.com/98065229/222304893-bec11f01-558b-48fd-8d4c-ad5db29aabc6.png)

**Comment by mahtjarohst** [comment]
Here's a better screen shot

![Screenshot_20230301_191513](https://user-images.githubusercontent.com/98065229/222305559-b850a074-dfda-420c-880f-e76117edb41d.png)

**Comment by rany2** [comment]
I'm guessing if this is occurring on other Flatpaks, then it's not a Brave issue?

**Comment by mahtjarohst** [comment]
Personally, I have not had it occur with other flatpaks. All chromium based browser flatpaks usually require a bit of tinkering to get the theme working in my experience. Brave flatpak is the only one I have had this issue with though. I found it easier to theme in Gnome than KDE. The adw-gtk3 actually has a flatpak theme, and that does work with Brave. You have to override it specifically for Brave.
