### ISSUE TITLE
Add write access to directories needed for PWA apps by default

### ISSUE THREAD

**Issue by erazemk** [flathub/com.brave.Browser#125]
I saw #7, but that doesn't seem related to my suggestion. To use PWAs I can of course manually add permissions for creating shortcuts using Flatseal, but I think it would be more user friendly (especially for those who have no idea what Flatseal is or how to use the command line program) to have access to the required directories (`~/.local/share/applications` and `~/.local/share/icons`) by default.

Screenshot for reference:
![image](https://user-images.githubusercontent.com/46302511/164746621-59e922c2-0cf3-427d-99e5-4f02a0152134.png)

**Comment by erazemk** [comment]
@rany2 Thanks for including the directories, but iirc when I did that manually it didn't fix the issue. I think the problem might be the same as here: https://github.com/flathub/com.google.Chrome/issues/91#issuecomment-1127042908

**Comment by rany2** [comment]
Seems like it needs `:create` permissions as well. Will do so!
