### ISSUE TITLE
U2F devices like trezor is not detected

### ISSUE THREAD

**Issue by NightProwler-dc** [flathub/com.brave.Browser#126]
yubikey as 2fa device works though. I wonder if it can be fixed by granting some permissions?

**Comment by TheEvilSkeleton** [comment]
Based on https://github.com/flatpak/flatpak/issues/2764, giving the app access to `--device=all` should work. However, it's a security risk.

**Comment by vorburger** [comment]
FTR https://github.com/flatpak/flatpak/issues/4405 proposes a (future, new, TBD) `device=usb option`.

> giving the app access to --device=all should work

According to e.g. https://github.com/xhorak/firefox-devedition-flatpak/issues/51, the following should presumably do that:

    sudo flatpak override --device=all com.brave.Browser

Unfortunately at least for me that didn't work, for a YubiKey on Fedora 36 Silverblue, where the same YK SK works in Firefox which Fedora Silverblue has "natively" (in `/usr/bin/firefox`, not as a Flatpack). My `journalctl` doesn't show any related errors from Brave - it appears that it simply doesn't "see" the SK.

> However, it's a security risk.

But that's "not worse" than running Brave without Flatpack?
