### ISSUE TITLE
[Question] Update time delay

### ISSUE THREAD

**Issue by BirdInFire** [flathub/com.brave.Browser#127]
I'm quite new on brave (on flathub) i just want to know the "normal" delay time (for update) before it's concidered as a bug (for example a new brave version is out now for some day).

I ask to see if there is a place to see where the update is (bug blocking etc) ?

Thanks

**Comment by rany2** [comment]
It seems that fedc is broken. `https://brave-browser-downloads.s3.brave.com/latest/release.version` points to a newer version but no PR was made by the bot.

**Comment by BirdInFire** [comment]
> It seems that fedc is broken. `https://brave-browser-downloads.s3.brave.com/latest/release.version` points to a newer version but no PR was made by the bot.

So it was a problem, when a bug like this arrive, it take normally how many time to be fixed ? (only ask out of curiosity since (again) i'm new when it come to flatpak update time).

I"m more like (oh only 3 day will open an issue in 5 day if there is nothing kind of guy) than OMG it's not up to date i will die (unless there is a critical security update of course).

**Comment by rany2** [comment]
Check https://github.com/flathub/flathub/issues/3092

**Comment by BirdInFire** [comment]
> Check [flathub/flathub#3092](https://github.com/flathub/flathub/issues/3092)

Thanks have subscribed and will close the issue when they have fixed it (like that if anyone else come for the same reason he/she will see it's already known.

**Comment by rany2** [comment]
It should be resolved now. https://github.com/flathub/com.brave.Browser/pull/128

Will test and merge

**Comment by BirdInFire** [comment]
> It should be resolved now. #128
> 
> Will test and merge

no problem thanks
