### ISSUE TITLE
Disable automatic updates

### ISSUE THREAD

**Issue by x80486** [flathub/com.brave.Browser#15]
Would be great if there is a way to disable the _check for updates_ in Brave.

I'm not sure how Brave (Flatpak) is able to update itself, unless it puts something in any of the XDG sub-directories 😒

**Comment by rany2** [comment]
Doesn't seem possible even with enterprise policies, see https://github.com/brave/brave-browser/issues/5576.

**Comment by rany2** [comment]
I'll keep this issue open until Brave implements something I could use to disable auto update.

**Comment by rany2** [comment]
I found this: https://github.com/brave/brave-core/blob/master/common/brave_switches.cc#L20-L21

I'll check if this disables auto updates

**Comment by rany2** [comment]
This should be fixed now
