### ISSUE TITLE
vaapi on wayland?

### ISSUE THREAD

**Issue by gothmog123** [flathub/com.brave.Browser#164]
is there any chance of getting it anytime in the foreseeable future?

**Comment by wooque** [comment]
VAAPI doesn't work on Wayland in Chromium and Chrome so it won't work in Brave until they fix that upstream

**Comment by smonsec** [comment]
Unfortunately an upstream issue, in development for years.

**Comment by rany2** [comment]
Yes, an upstream issue. All Chromiums have this issue unless they apply some patch. Unfortunately this is not feasible at the moment because we are getting binaries from Brave themselves. It's also not feasible to build this ourselves because we need their API keys.
