### ISSUE TITLE
Remove firebaseapp and accounts.google from websites that can always use cookies by default

### ISSUE THREAD

**Issue by hrrd** [flathub/com.brave.Browser#193]
the deb. package brave for example has nothing similar to that. would be nice if this would be removed.

**Comment by rany2** [comment]
I've noticed this too but I just thought it was a Brave bug that affects all other packaging formats. In any case this shouldn't happen only for their zip and seems like something they should be made aware of

**Comment by rany2** [comment]
I've reported this issue in https://github.com/brave/brave-browser/issues/25647

**Comment by hrrd** [comment]
Well if this occurs in the nightly build of brave than maybe its a issue which caused by the official brave team. i checked the brave stable deb package and there was no such setting.

**Comment by rany2** [comment]
.deb has the same defaults, closing
