### ISSUE TITLE
Brave icon too fat

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.brave.Browser#2]
The left one is Brave Flatpak, and the right one is the official Brave browser. The Brave Flatpak browser's icon is really fat. I tried in my VM and in my current install. I'm using stock Fedora 33.

![image](https://user-images.githubusercontent.com/50847364/96325491-36c23200-0ff6-11eb-927a-3b0867c5536b.png)

**Comment by x80486** [comment]
Same happens for me in Arch Linux — the Flatpak lion has mumps :sunglasses:

It's definitely the SVG. Brave should be able to provide the official one — and if the one stored in the repository is the official one it is a _malformed_ SVG.

**Comment by TheEvilSkeleton** [comment]
Okay, I found the official icon here: https://github.com/brave/brave-browser/blob/master/docs/source/_static/brave-release.svg

I'm not sure if licensing works, but we should be able to just use it right?

**Comment by TheEvilSkeleton** [comment]
@bsclifton (sorry for the ping) I'm not sure how this works, but are we allowed to use [this icon](https://github.com/brave/brave-browser/blob/master/docs/source/_static/brave-release.svg) for the flatpak?

**Comment by bsclifton** [comment]
cc: @bradleyrichter - OK to use our images?
