### ISSUE TITLE
Two finger Swipe Gesture to go Forward/Backward doesnt work

### ISSUE THREAD

**Issue by Raul1198** [flathub/com.brave.Browser#221]
two finger swipe doesnt seem to work on Fedora 37 Workstation , i tried on win11 and ther it was working

**Comment by rany2** [comment]
It doesn't work on the .deb version for me either, I don't think it's a flatpak issue.

**Comment by Raul1198** [comment]
> It doesn't work on the .deb version for me either, I don't think it's a flatpak issue.

Could it be something like brave not supporting gesture in Wayland. Like we have recently got gesture on Firefox with Wayland
