### ISSUE TITLE
grant.rewards.brave.com fails to connect

### ISSUE THREAD

**Issue by jeroenev** [flathub/com.brave.Browser#231]
Seems like some users have issues with brave rewards being paused and unable to be re-activated because of an error.
After checking further it seems like it might be related to the flatpak version, see: https://github.com/brave/brave-browser/issues/26995
![image](https://user-images.githubusercontent.com/10954827/206153008-21373caa-034a-4a96-a3c3-5272dc72bf59.png)
can anyone check if this is related to flatpak?

**Comment by bbhtt** [comment]
Seems like an issue on their end? https://github.com/brave/brave-browser/issues/26995#issuecomment-1355240108

**Comment by jeroenev** [comment]
yep, can be closed I think
