### ISSUE TITLE
[Ozone+PipeWire] Cursor theme is defaulted to xcursor instead of the system default

### ISSUE THREAD

**Issue by AndrejSh3** [flathub/com.brave.Browser#234]
Brave defaults to a cursor that looks like the xcursor whenever it is the focused window.
I currently have no flatpak overrides, and both ~/.icons and ~/.local/share/icons are completely empty.
Other flatpak apps like flatseal, gnome-calculator, vscode, etc. work as expected.

Cursor icon next to brave browser window, hovering over the background:
![Screenshot from 2022-12-12 10-44-55](https://user-images.githubusercontent.com/61660699/207013774-7ef194f1-869e-4f20-8026-d4a7008a9e68.png)

Cursor icon over brave browser window:
![Screenshot from 2022-12-12 10-45-01](https://user-images.githubusercontent.com/61660699/207013835-85f4a3ff-e89f-49a5-907f-c1074186f5ac.png)

System info: Fedora Silverblue 36, Wayland

Edit: Additional observation, this only happens whenever I switch the ozone platform to wayland and enable WebRTC PipeWire support flags in brave://flags

**Comment by bbhtt** [comment]
Does `flatpak run --env=XCURSOR_PATH=/run/host/share/icons:/run/host/user-share/icons com.brave.Browser` work with native wayland in Brave & Flatpak (ie. --nosocket=x11)?

It's noticeable more here I think.

Running with that: 

![image](https://user-images.githubusercontent.com/62639087/209669493-13aaee17-def1-4167-a4f8-0b6a4fbc078c.png)

Without that:

![image](https://user-images.githubusercontent.com/62639087/209669757-1572da3f-1176-49ee-967f-f8ea15f01358.png)

**Comment by rany2** [comment]
Seeing the experimental nature of Ozone/Pipewire on Chromium. I will close this issue until the flag is enabled by default.
