### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by mihaiplesa** [flathub/com.brave.Browser#250]
Brave now has arm64 on all channels.

**Comment by rany2** [comment]
Doesn't seem to be the case for Linux builds. Right now we're just pulling GitHub release artifacts and it doesn't seem to be there. Is this something I could find in one of the Linux repos from Brave?

**Comment by mihaiplesa** [comment]
We do publish Linux arm64 for most builds like https://github.com/brave/brave-browser/releases/tag/v1.48.171

**Comment by rany2** [comment]
Thanks, I was infact checking the nightly builds.On 1 Mar 2023 8:41 AM, Mihai PLESA ***@***.***> wrote:
We do publish Linux arm64 for most builds like https://github.com/brave/brave-browser/releases/tag/v1.48.171

**Comment by mihaiplesa** [comment]
Might be broken now, fixed in https://github.com/flathub/com.brave.Browser/pull/283
