### ISSUE TITLE
Slow unresponsive when more than one window open.

### ISSUE THREAD

**Issue by mahtjarohst** [flathub/com.brave.Browser#262]
I'm going to elaborate further on this, I am running it on Fedora Kinoite, and it only seems to do this when I have more than one window open and the the other window is on a different profile. I will have my work profile open on one Activity/Workspace and my personal profile on another. When I try to scroll, it takes about 10 seconds to respond to the scroll, click, refresh etc.

**Comment by rany2** [comment]
Did you harden your Brave browser? Maybe you disabled access to your GPU?

**Comment by mahtjarohst** [comment]
> Did you harden your Brave browser? Maybe you disabled access to your GPU?

I don't believe I did. It may have something to do with the sandboxing. I mostly notice it if I have a video playing in one profile, and scrolling in my work profile.

**Comment by rany2** [comment]
This is a sign that you are not getting hardware acceleration for video decode and that your CPU is actually the bottleneck. Check `chrome://gpu/` if it says that video decode is hardware accelerated.

**Comment by rany2** [comment]
Nope, looks good to me.

**Comment by rany2** [comment]
Actually it's worth noting that if you're viewing YouTube or NetFlix, it is most likely serving AV1 which I don't think any Linux distro has hardware decode support for. Can you check if the CPU load when watching some video? If it's maxing out then I guess we figured out the culprit.
