### ISSUE TITLE
Ready for Flathub?

### ISSUE THREAD

**Issue by Spacesurfer** [flathub/com.brave.Browser#28]
I've been running Brave from Flathub-Beta for a while and haven't come across any other issues. Just wondering at what point it will be available from Flathub proper? Any other help needed to get it moved out of beta?

**Comment by TheEvilSkeleton** [comment]
The Brave flatpak depends on the Chrome flatpak, so we need to wait for the latter to switch to the stable repos so we can make the switch.

**Comment by WhyNotHugo** [comment]
Hi! I'd like to help figure out if this dependency can be removed (e.g.: stop waiting for the Chrome flatpak).

I'm looking at the source in this repo, and can't see any references to chrome. What exactly is the blocking dependency here?

**Comment by rany2** [comment]
@WhyNotHugo The blocker isn't Chrome but Zypak. Zypak is still experimental for Chromium-based browsers.

**Comment by WhyNotHugo** [comment]
Ah, I see. How is it that `com.github.Eloston.UngoogledChromium` works though? They seem to be skipping `zypak` entirely.

**Comment by rany2** [comment]
Ungoogled Chromium compiles from source with patches that implement sandboxing.

**Comment by refi64** [comment]
There are some other weird-ish issues as well, most notably, checking the box to install an icon on the desktop will create a launcher entry that doesn't actually work. We're trying to resolve these via, well, epic hacks, but it'll be a bit regardless.

With Chromium stuff like this is less of an issue because we can patch out anything we don't need.

**Comment by WhyNotHugo** [comment]
Have you tried building brave from source (much like the chromium package does)?

I'd be willing to give it a shot if you haven't -- but won't bother if you've already figured out it's a dead end.

**Comment by rany2** [comment]
@WhyNotHugo 

> I'd be willing to give it a shot if you haven't -- but won't bother if you've already figured out it's a dead end.

Building Brave is pretty annoying because it involves NPM. I don't want to bother but if someone is willing to put in the effort and it works, then I'll accept the PR. I stopped using both UGC and Brave in favor of Firefox
