### ISSUE TITLE
[Ozone+HiDPI] Mouse cursor is tiny

### ISSUE THREAD

**Issue by BirdInFire** [flathub/com.brave.Browser#284]
On my HiDPI laptop with Ozone enabled and fractional scaling set to 125% the mouse cursor is very tiny and unthemed.

This bug was introduced with: `org.freedesktop.Platform/x86_64/22.08`

Apps using the same runtime that have this issue:
- Signal

Unaffected apps using the same runtime:
- LibreOffice
- LibreWolf

**Comment by rany2** [comment]
I could have this fix integrated into the Flatpak itself. There is no need for it to be in the README.

**Comment by rany2** [comment]
It will be closed when https://github.com/flathub/com.brave.Browser/pull/286 or https://github.com/flathub/com.brave.Browser/pull/285 are merged.

**Comment by rany2** [comment]
@BirdInFire It just needs 2-3 hours for the update to propagate to Flathub.

**Comment by refi64** [comment]
Worth noting I [fixed this in cobalt](https://github.com/refi64/cobalt/commit/02d96c773f230f41f1b29e772403edfd2a60de28), it just took a hot minute for it to roll out to the baseapp due to some unrelated issues with the external-data-checker setup there.

**Comment by refi64** [comment]
The environment variable is set *inside* the app, so it should work
