### ISSUE TITLE
Gnome 44 + Fedora 38 BUG

### ISSUE THREAD

**Issue by ghost** [flathub/com.brave.Browser#301]
On Gnome 44 with fedora silverblue 38 the .desktop argument @@u %U @@ make crash the app (on wayland).
when the arg is replaced by : %U alone the app stop crashing. (tested with ozone platform to wayland).

Can you (or anyone else) replicate and fix it if i'm not the only one ?

Edit fedora 38 is on pre-release i tell before to fix the bug before the release happen (if you can replicate).

**Comment by rany2** [comment]
@BirdInFire That is added by Flatpak during install in order to allow you to "open with" Brave without giving it filesytsem permissions.

@refi64 Any ideas as what is going on here? Sounds like a Flatpak bug to me

**Comment by refi64** [comment]
Does it work if you do `flatpak run com.brave.Browser @@U @@` from the terminal, or does it also fail? If it does fail, could you post the output?

This does very much sound like a Flatpak or portal-related issue.
