### ISSUE TITLE
Can not add custom filter in Shields

### ISSUE THREAD

**Issue by tazihad** [flathub/com.brave.Browser#310]
I am trying to add a custom filter list. But updates failed. And if I click on source. It says sourse is moved. It points to this location. 
```
file:///home/USER1/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser/Default/FilterListSubscriptionCache/VrmuJcGQh91GpGtOlaGOKVr1IdDUirZCmnrvwZ9vkZc=/list_text.txt
```

![Screenshot_20230403_013622](https://user-images.githubusercontent.com/19417232/229375099-55b41ed5-916a-4423-af13-e3668f737744.png)
![Screenshot_20230403_013731](https://user-images.githubusercontent.com/19417232/229375104-c918889f-eb5d-4616-ae4c-0e66fd9673ca.png)

**Comment by rany2** [comment]
With the same filter you tried to use, I can't reproduce this anymore: ![image](https://user-images.githubusercontent.com/71077389/232229629-06816d68-3743-4862-aada-90e8af7fb7d9.png)

Seems to work fine, possibly a Brave bug that got fixed.
