### ISSUE TITLE
--no-sandbox packaging

### ISSUE THREAD

**Issue by guria9** [flathub/com.brave.Browser#335]
hello,

im so confused and hope someone can help me regarding packaging another chromium app.
you use `bsdtar -xf brave.zip -C /app/brave`

-rwxr-xr-x. 1 user user    220880 Apr 20 22:13 chrome-sandbox

but i get the hole time:

```
chrome-sandbox is owned by root and has mode 4755.
[0501/085239.920589:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
```

whats the trick, where do you set the file permissions and owner?

i tried hard but i dont get it.

**Comment by guria9** [comment]
How do you package the flatpak. I looked into the workflow of this repo as well as the .yaml for building but i dont see how you set / ensure the file owner and permission of chrome-sandbox

**Comment by rany2** [comment]
1. https://docs.flatpak.org/en/latest/flatpak-builder.html
2. `chrome-sandbox` ownership doesn't matter, it is not used. The file just has to exist to get Chromium to use Zypak.

**Comment by guria9** [comment]
dammet i wasted so much time trying to get it to work.

but i dont see how you run --no-sandbox as run flag.

**Comment by rany2** [comment]
You don't need `--no-sandbox` if you run with zypak.
