### ISSUE TITLE
Brave sync not working

### ISSUE THREAD

**Issue by mahtjarohst** [flathub/com.brave.Browser#339]
I had this issue on two of my machines. I was only able to fix it by deleting the sync account, deleting the brave keys from kwalletmanager, then creating a new sync account passphrase. Luckily I was able to preserve my data from the android version of Brave. I hope this helps others experiencing this issue.

**Comment by exilvm** [comment]
I can confirm the issue and yes i had to do the same to fix it.

**Comment by exilvm** [comment]
When it happened on my second machine I fixed the issue by simply entering `brave://sync-internals` and clicking on the Disable Sync (Clear data) button.

**Comment by AlexeyBarabash** [comment]
Could you provide more details? Does this issue happen on Linux KDE?

**Comment by AlexeyBarabash** [comment]
ah, `kwalletmanager` - sorry, this is known issue.
Fix https://github.com/brave/brave-core/pull/18404 is in master and will reach Stable version in the next maintenance release

**Comment by rany2** [comment]
Thanks for the details @AlexeyBarabash, closing!
