### ISSUE TITLE
Can't play videos from Google Drive

### ISSUE THREAD

**Issue by Zlopez** [flathub/com.brave.Browser#34]
Today I tried to replay recording from one meeting and the link was redirecting me to google drive. When I tried to play it, it either didn't do anything or the player crashed with: "An error occurred. Please try again later." I thought that this could be blocked by brave shield, so I temporary disabled it for the page but without success.

After that I tried to play the video with Firefox in Flatpak and it was working without issue.

Here is the console output from the Brave:
[drive.google.com-1617887954078.log](https://github.com/flathub/com.brave.Browser/files/6278939/drive.google.com-1617887954078.log)

Unfortunately I can't give you access to the video itself, but I can provide any additional info if needed.

**Comment by TheEvilSkeleton** [comment]
@Zlopez sorry for the late response. Can you try it on a non flatpak'd Brave, i.e. from a Deb or RPM?

**Comment by rany2** [comment]
@Zlopez Also Google Drive won't play videos when you block 3rd party cookies

**Comment by rany2** [comment]
Closing because it's not a flatpak issue: 
* https://github.com/brave/brave-browser/issues/1122
* https://github.com/brave/brave-browser/issues/9986
