### ISSUE TITLE
Wayland fractional scaling is buggy with v113

### ISSUE THREAD

**Issue by TheComputerM** [flathub/com.brave.Browser#344]
The UI scaling looks fine, but the app behaves as if the scaling is 2x instead of 1.5x, example cursor is larger, and it is not in the position it appears to be.

https://bugs.chromium.org/p/chromium/issues/detail?id=1356014
https://github.com/flathub/org.chromium.Chromium/commit/eea7af903decb3a3b9bb6fdacbb55d24a90e18f3

Same issue with microsoft edge v113

**Comment by TheComputerM** [comment]
Fractional scaling is not an issue with the latest chromium flatpak.

**Comment by BirdInFire** [comment]
fixed in last version (of brave), hope to see it soon as flatpak :) 
https://github.com/brave/brave-browser/issues/30137#event-9273319622

**Comment by Pythoner6** [comment]
> Fractional scaling is not an issue with the latest chromium flatpak.

Yeah I think the chromium flatpak backported the patch that fixed this issue before the issue was shipped upstream. As mentioned, a new brave version has been released today that includes the upstream fix and so hopefully we'll get the updated flatpak soon.
