### ISSUE TITLE
"Set as Default Browser" prompt on every launch

### ISSUE THREAD

**Issue by imbev** [flathub/com.brave.Browser#356]
My host OS is openSUSE Tumbleweed with KDE Plasma. Brave Browser version is 1.51.118, although this has been happening since installation.

Literally every time that I start Brave, I have to close the default browser prompt. This ignores my default applications setting which is already set to Brave. This is the only installed version of Brave on the system.

**Comment by TAmzid2872** [comment]
The same error also happens to me on the same version (1.51.118) on Linux Mint 21.1 CInnamon.

**Comment by github0004** [comment]
Having the same issue and can't find a fix either. Running Fedora Silverblue.

Running: xdg-settings get default-web-browser
Returns: com.brave.Browser.desktop

Also my ~/.config/mimeapps.list contains:
[Added Associations]
x-scheme-handler/http=com.brave.Browser.desktop;
application/xhtml+xml=com.brave.Browser.desktop;
text/html=com.brave.Browser.desktop;
x-scheme-handler/https=com.brave.Browser.desktop;

[Default Applications]
x-scheme-handler/http=com.brave.Browser.desktop
application/xhtml+xml=com.brave.Browser.desktop
text/html=com.brave.Browser.desktop
x-scheme-handler/https=com.brave.Browser.desktop


I noticed "x-scheme-handler/http=com.brave.Browser.desktop;" was in other people's config and wasn't in mine but adding it and rebooting had no effect.

**Comment by imbev** [comment]
My ~/.config/mimeapps.list
```
[Added Associations]
inode/directory=org.kde.dolphin.desktop;
x-scheme-handler/geo=wheelmap-geo-handler.desktop;
x-scheme-handler/http=com.brave.Browser.desktop;
x-scheme-handler/https=com.brave.Browser.desktop;

[Default Applications]
inode/directory=org.kde.dolphin.desktop;
x-scheme-handler/geo=wheelmap-geo-handler.desktop;
x-scheme-handler/http=com.brave.Browser.desktop;
x-scheme-handler/https=com.brave.Browser.desktop;
```

**Comment by refi64** [comment]
This is [a bug in Brave itself](https://github.com/brave/brave-browser/issues/30791), it's default browser check doesn't handle the case where you can't actually inspect or set the default.

**Comment by EyeCantCU** [comment]
Running with --no-default-browser-check somewhat remedies this for the time being
