### ISSUE TITLE
Widevine not detected even though Widevine is Enabled in settings

### ISSUE THREAD

**Issue by shakeelansari63** [flathub/com.brave.Browser#357]
I have widevine enabled in setting, still Netflix and other video streaming sites complain for DRM.

Widevine is Enabled - 
![image](https://github.com/flathub/com.brave.Browser/assets/8319053/026ea095-73df-4888-bbce-2545fdca33b3)

I have tried to Update widevine from brave://components
![image](https://github.com/flathub/com.brave.Browser/assets/8319053/dd471c12-2f4e-4d4f-ab97-798dc3b37369)

But still getting Protected Content error on Netflix
![image](https://github.com/flathub/com.brave.Browser/assets/8319053/f28fdb78-2c8c-446b-8365-66fc273356d7)

This is version of Brave installed from Flathub
![image](https://github.com/flathub/com.brave.Browser/assets/8319053/15398014-0cd2-449b-8298-6f88c83808a5)

Let me know if you need any more detail

**Comment by shakeelansari63** [comment]
Ran Brave from terminal and I see this error - 
![image](https://github.com/flathub/com.brave.Browser/assets/8319053/2bf74b9d-b427-4e69-8c4e-ea72931954e3)

May help you debugging the issue.

**Comment by rany2** [comment]
This seems like a Zypak issue to me, does it work if you run with `--disable-sandbox`?

**Comment by shakeelansari63** [comment]
Nope, `--disable-sandbox` option does not help. Same error

**Comment by archerallstars** [comment]
This issue is still happening on Brave v1.65.126, with Widevine Content Decryption Module v4.10.2710.0.

**Comment by rany2** [comment]
BTW, I was mistaken; the flag is now `--no-sandbox`

**Comment by archerallstars** [comment]
@rany2 Widevine works with `--no-sandbox` flag. I tested with Prime Video.

**Comment by rany2** [comment]
@refi64 can you take a look, it seems like Zypak is broken with Widevine again. I'm setting ExposeWidevine to true in cobalt so I think it should be working?

**Comment by archerallstars** [comment]
What I found as a workaround is to allow `filesystem=host-os`, as shown in the screenshot below:

![ss](https://github.com/flathub/com.brave.Browser/assets/1403194/5208b8d0-9f7c-4380-a641-caa94a30d211)

But I don't know what's the security impact of allowing this. Does this make it less secure than the non-Flatpak version? But this should be more secure than the `--no-sandbox` flag, right?

**Comment by rany2** [comment]
@archerallstars It's for sure for secure than `--no-sandbox`

**Comment by Digitalone1** [comment]
Is this issue resolved? I'd like to switch to Flatpak version, but if Widevine it's not working, I will stay on the distro package.

**Comment by shakeelansari63** [comment]
> Is this issue resolved? I'd like to switch to Flatpak version, but if Widevine it's not working, I will stay on the distro package.

Yes, I can confirm this issue has been fixed.  
I am using Brave flatpak since more than 6 months without any issues.
