### ISSUE TITLE
Spell check dictionary download failed

### ISSUE THREAD

**Issue by ozboss** [flathub/com.brave.Browser#368]
Trying to download a dictionary other then English fails:
![image](https://github.com/flathub/com.brave.Browser/assets/32305849/17a8c17a-2fa5-4c8d-bb01-eff6385810e0)

Brave version installed by Flatpak:
![image](https://github.com/flathub/com.brave.Browser/assets/32305849/2c3c3583-71a2-4c37-be5e-7018774d9b2a)

Running Brave from terminal does not provide any additional information.

For anybody looking for a workaround:
`wget -P ~/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser/Dictionaries https://dict.brave.com/edgedl/chrome/dict/de-DE-3-0.bdic`

If you need a dictionary for another language then german look for the name of the .bdic file for your language here:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/hunspell_dictionaries/

**Comment by rany2** [comment]
I don't seem to have this issue anymore, I think it's fixed.
