### ISSUE TITLE
Can't leave sync chain

### ISSUE THREAD

**Issue by Zlopez** [flathub/com.brave.Browser#38]
Hi,

I found out that my flatpak Brave is not synced to any other device. For some reason it has it's own sync chain. I decided to leave the current sync chain and add the flatpak Brave to existing sync chain. Unfortunately when I navigate to `Settings -> Manage your synced devices` and click on `Leave Sync Chain` I got the confirmation dialog press OK and nothing happens. I can still see the sync chain is active in `Settings -> Manage your synced devices`.

**Prerequisites**:
Your flatpak Brave is already in Sync Chain

**How to reproduce**:
1. Go to `Settings -> Manage your synced devices`
2. Click  `Leave Sync Chain`
3. Click `OK` on confirmation dialogue

**Expected result**:
Flatpak Brave is removed from Sync chain

**Current result**:
Flatpak Brave is still in Sync chain

**Comment by rany2** [comment]
Could it be that the old libsecret issues borked your profile?

**Comment by Zlopez** [comment]
This could be reason why I'm on separate chain, but I still should be able to leave it.

**Comment by rany2** [comment]
I meant can you try a new profile and see if it works there, if it does then we don't have an issue

**Comment by Zlopez** [comment]
Could you give me a direction how can I create a new profile?

**Comment by rany2** [comment]
@Zlopez 

Close brave completely (`flatpak kill com.brave.Browser`) and run the following `mv ~/.var/app/com.brave.Browser{,.bak}`. Now test the new profile.

If you want to restore your old profile, delete `~/.var/app/com.brave.Browser.bak` and rename it back to it's original name ( `mv ~/.var/app/com.brave.Browser{.bak,}`).

**Comment by Zlopez** [comment]
You were right, I recreated the profile and the sync now works.

**Comment by Gluvii** [comment]
> @Zlopez
> 
> Close brave completely (`flatpak kill com.brave.Browser`) and run the following `mv ~/.var/app/com.brave.Browser{,.bak}`. Now test the new profile.
> 
> If you want to restore your old profile, delete `~/.var/app/com.brave.Browser` and rename it back to it's original name ( `mv ~/.var/app/com.brave.Browser{.bak,}`).

Hello wheere do I put the commands I do not know where to place them,.
