### ISSUE TITLE
Japanese/Korean Character Support (symbols missing from included fonts)

### ISSUE THREAD

**Issue by tommydrum** [flathub/com.brave.Browser#394]
![See this](https://github.com/flathub/com.brave.Browser/assets/950485/8ca8b03b-ff0d-408f-88ff-f547b81a291b)

Going to https://www.yahoo.co.jp/ with the Brave Flatpak reveals all of the Japanese characters (Hiragana, Katakana, and Kanji) are all missing from the fonts included in the Flatpak. Testing the FireFox flatpak, the characters do indeed work, suggesting there is something missing within the package.

From quick testing, this affects Japanese and Korean, see coupang.com for Korean.

**Comment by tommydrum** [comment]
For clarification, my host OS is Fedora Silverblue 38, and I do actively use Japanese within it, within all types of applications as well as typing. Host is not the problem here.

**Comment by rany2** [comment]
Dup of https://github.com/flathub/com.brave.Browser/issues/315
