### ISSUE TITLE
2FA authentication with my yubikey fails

### ISSUE THREAD

**Issue by fmoreau** [flathub/com.brave.Browser#443]
Hello,

When I'm asked to authenticate myself with my yubikey, after pressing the button on my yubikey, brave fails and show the following error:

> The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.

Let me know if you need more info and in this case please describe the steps to retrieve them.

Thanks.

**Comment by theonejj** [comment]
I have the same issue, seem to happen only on Brave
I am on Brave Version 1.59.124 Chromium: 118.0.5993.117 

# Step to reproduce:
- Start Brave and open https://www.yubico.com/genuine/
- Click Verify
- You will get a prompt asking:
![image](https://github.com/flathub/com.brave.Browser/assets/55584062/3d00552d-da51-4126-8bef-77670d41f7da)

- Insert your yubikey and touch it
- You will get this error: `Operation failed
The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.` 

I also tried: com.github.Eloston.UngoogledChromium but it crashed after touching the Yubikey

org.chromium.Chromium 118.0.5993.117 works as expected.
But it is using different prompts

I hope this information helps

**Comment by theonejj** [comment]
I just updated to version: 1.60.110 Chromium: 119.0.6045.105
The issue seems to be resolved.
My Yubikey is working as expected
