### ISSUE TITLE
Window titlebar buttons misplaced when using vertical tabs

### ISSUE THREAD

**Issue by mrust1219** [flathub/com.brave.Browser#467]
Only when using vertical tabs, you can see the titlebar buttons are not centered.

Fedora 39 Silverblue

I am also using the adw-gtk3-theme.

This issue was not present prior to the latest update.

![Screenshot from 2023-11-02 19-22-46](https://github.com/flathub/com.brave.Browser/assets/98065229/e19e322d-e33f-47ea-ae69-c85ce8520fd9)
![Screenshot from 2023-11-02 19-24-16](https://github.com/flathub/com.brave.Browser/assets/98065229/aba52f88-6aac-4d8f-b249-a5ff4a004429)

**Comment by Zlopez** [comment]
I have the same issue on Fedora 39 Silverblue

**Comment by ilovethensa** [comment]
Same issue on arch and fedora 39

**Comment by Zlopez** [comment]
With the latest update it seems to be fixed, at least for me.
