### ISSUE TITLE
Wayland: Cannot Download if Prompt Before Save Enabled

### ISSUE THREAD

**Issue by pjkaufman** [flathub/com.brave.Browser#472]
Hey, I recently moved to Wayland and noticed that when trying to run downloads Brave would go through the process of the download, but when it came time to display the download option, it would not do anything. I was curious what might be going on, so I tried running running with `brave://flags/#ozone-platform-hint` set to wayland. But I got the same result. With that happening, I reset the ozone platform hint to default. Then I tried turning off the option to prompt me for the download location before each download. This fixed the issue.

I am using braving version 1.60.110 on Sway 1.7 on Pop OS 22.04 if that helps at all.

Please let me know if more info is needed.

**Comment by rany2** [comment]
Unfortunately there is not much I could do, Wayland support is still experimental and we're just distributing the Brave binary here.

**Comment by pjkaufman** [comment]
Hey. I think the issue was with the portals not being configured correctly. I got the portal setup with the right environment variables and it started working.
