### ISSUE TITLE
latest version is crashing on ARM / Librem5 / PureOS

### ISSUE THREAD

**Issue by mel-geo** [flathub/com.brave.Browser#473]
Looks like the most recent version or two has broken brave browser on Librem5. it crashes right away on launch.

to make it work i have to downgrade like so:

sudo apt install brave-browser=1.59.124

if this could be fixed that would be great. Brave is one of the best options to run web apps at the moment so it is very important to many of us on mobile linux.

Thanks!

**Comment by rany2** [comment]
This for the flatpak, not apt package.
