### ISSUE TITLE
Media playback slows browser response times

### ISSUE THREAD

**Issue by kratosok** [flathub/com.brave.Browser#5]
So if I have video playback going in one brave tab, flatpak brave seems to slow down responsiveness. Normal responsiveness seems to occur after playback tab is closed.

I'd love to help troubleshoot the issue as I'm very glad to have Brave in a flatpak.

OS:Fedora Silverblue.

**Comment by refi64** [comment]
Is this specific to the Flatpak?

**Comment by kratosok** [comment]
I thought it was, but on further testing it seems to happen to the regular version as well, so I will report it over there instead. We can close this.
