### ISSUE TITLE
Move Brave to stable

### ISSUE THREAD

**Issue by x80486** [flathub/com.brave.Browser#53]
I've been using the Brave flatpak since day `0`, and while there were a few rough edges initially, I don't see why it cannot be "promoted" these days to the stable branch...unless there is/are outstanding issue(s) I'm not aware of — or I just don't use.

---

OK, I checked the other issue (already closed) very similar to this one. I would recommend leaving one of these opened so we can track this.

**Comment by rany2** [comment]
Most of the issues in this flatpak are the same as the ones in [flathub/com.google.chrome](https://github.com/flathub/com.google.chrome). So when [flathub/com.google.chrome](https://github.com/flathub/com.google.chrome) moves to master I will do the same.

**Comment by alvarlagerlof** [comment]
Isn't Brave based on Chromium, not Chrome?

**Comment by TheEvilSkeleton** [comment]
Yes, Brave is based on Chromium. However, the Brave Flatpak is based on the Chrome Flatpak.

**Comment by tazihad** [comment]
please move this to stable. i don't see any reason for it to be in beta. I am using it for couple of months. Everything works perfect.

**Comment by TheEvilSkeleton** [comment]
We already explained why we won't do it yet. Please wait.

**Comment by TheEvilSkeleton** [comment]
https://github.com/flathub/com.microsoft.Edge/issues/88#issuecomment-1086420380

**Comment by Master811129** [comment]
@TheEvilSkeleton chrome is now available on flathub can you put your package now?

**Comment by rany2** [comment]
Done

**Comment by TheEvilSkeleton** [comment]
The stable release should be published in 3-4 hours.

**Comment by rany2** [comment]
The beta branch now uses Brave Beta.
