### ISSUE TITLE
Auto Scrolling Support

### ISSUE THREAD

**Issue by Raul1198** [flathub/com.brave.Browser#567]
autoscrolling  when mouse middle clicked ,

**Comment by rany2** [comment]
Not possible on Linux. You might want to create an issue at https://github.com/brave/brave-browser/

**Comment by Raul1198** [comment]
i did some searching and was able to make auto scroll work on Brave Flatpak, this and experimental flag chrome://flags/#middle-button-autoscroll, source - https://github.com/brave/brave-browser/issues/959
