### ISSUE TITLE
Brave stopped working with OzonePlatform Wayland since 1.65.114

### ISSUE THREAD

**Issue by Malom-ctrl** [flathub/com.brave.Browser#576]
For those who had previously set the chrome/brave OzonePlatform flag to Wayland, Brave is likely refusing to launch since the last update. Here is how to fix it :

- Go to **~/.var/app/com.brave.Browser/config**
- Create a file named **brave-flags.conf** if it doesn't already exist.
- In brave-flags.conf, add the following line :
`--ozone-platform=wayland`
- Launch Brave, it should now work
- If it still doesn't work make sure Brave's flatpak has the Wayland permission (You can do that using Flatseal)

Hope this helps.

**Comment by zeroskyx** [comment]
Works like a charm -- thanks mate!

**Comment by mak448a** [comment]
You mean ~/.config/BraveSoftware/Brave-Browser/brave-flags.conf? I tried that and it didn't work.

**Comment by zeroskyx** [comment]
> You mean ~/.config/BraveSoftware/Brave-Browser/brave-flags.conf? I tried that and it didn't work.

It's directly in `~/config/` without any additional sub-directories. If the file does not exist, simply create it and you should be good to go 🙂

**Comment by mak448a** [comment]
Oh ok! 👍🏻

**Comment by mak448a** [comment]
@zeroskyx It's still running on xwayland even though I did that :thinking:

**Comment by zeroskyx** [comment]
Check if you still have experimental flags (`brave://flags`) enabled (mainly the ozone platform override), and also double-check that Brave is actually consuming `~/.config/brave-flags.conf`.

Do do the latter:
1. Remove the file, start Brave and ensure that `brave://gpu/` lists `Ozone platform` = `x11`
1. Close Brave and create `~/.config/brave-flags.conf` again with only the content `--ozone-platform=wayland`
1. Re-start Brave and ensure that `brave://gpu/` lists `Ozone platform` = `wayland` and also has `--ozone-platform=wayland` in the `Command Line` field
1. If the last step did not work, try to put something else into `~/.config/brave-flags.conf` like `--incognito` and check if re-starting the browser opens it incognito
1. If that still does not work, Brave somehow does not respect the file :disappointed:

Note: ensure that all Brave instances are terminated (`killall brave`) to ensure that it takes the new configuration.

**Comment by mak448a** [comment]
I added `--incognito` to brave-flags.conf and it still doesn't respect it. However, now `brave-browser --ozone-platform=wayland` works for me.

**Comment by bbb651** [comment]
PWAs are also completely broken unless an existing instance of brave that isn't broken is already open, and they do not pick up `brave-flags.conf`, they can be fixed by manually editing the `brave-*.desktop` entries

**Comment by refi64** [comment]
https://github.com/flathub/org.chromium.Chromium/issues/385

> This is an [upstream bug](https://issues.chromium.org/issues/329678163) and specifically applies if you set the "Preferred Ozone platform" / `ozone-platform-hint` option. You should be able to run Chromium with `--ozone-platform=wayland` to work around it.

**Comment by cyangalaxy** [comment]
Hm...I did this workaround 1-2 days ago, and while it _does_ work, now my Brave seems to freeze occassionally... :S

I would have a couple tabs open, scroll & interact with a webpage, and then Brave is frozen all of a sudden. I close & re-open Brave, and I'm met with "Brave crashed. Restore windows?"

I've switched to Firefox as my main now (I like it equally as much), and keep Brave as backup. Since it appears to be a general Chromium bug, I'll keep an eye if the Chromium team fixes this.

**Comment by mihaiplesa** [comment]
https://github.com/brave/brave-core/pull/23166

**Comment by mihaiplesa** [comment]
Shipped in https://github.com/brave/brave-browser/releases/tag/v1.65.122

**Comment by sojusnik** [comment]
> Shipped in https://github.com/brave/brave-browser/releases/tag/v1.65.122

I'm currently using Version 1.65.122 (Chromium: 124.0.6367.82) on Ubuntu with Wayland, but with ozone platform = wayland it's still on X11:

![grafik](https://github.com/flathub/com.brave.Browser/assets/1245718/f2d8c663-3444-40f6-9e8b-a642a7c6dd7f)

![grafik](https://github.com/flathub/com.brave.Browser/assets/1245718/f8a23227-ed23-447c-8173-16a65ec7b6c3)

![grafik](https://github.com/flathub/com.brave.Browser/assets/1245718/82309af4-d2fa-484f-9e92-09f0b8e05de4)

**Comment by mihaiplesa** [comment]
@sojusnik that sounds like a different issue, have you looked through https://github.com/brave/brave-browser/issues?

**Comment by loeeeee** [comment]
I was using fedora and running Brave-nightly, and I met the same problem. To disable the ozone flag, I ran 
```bash
brave-browser-nightly --no-experiments
```
It opens the browsers with all the flag disabled. And then I went to brave://flags to disable the ozone flag.

**Comment by Malom-ctrl** [comment]
> I was using fedora and running Brave-nightly, and I met the same problem. To disable the ozone flag, I ran
> 
> ```shell
> brave-browser-nightly --no-experiments
> ```
> 
> It opens the browsers with all the flag disabled. And then I went to brave://flags to disable the ozone flag.

By doing so you no longer run your browser with Wayland but with X11 instead, which is probably not what you want if you changed your ozone flag to use Wayland in the first place.
