### ISSUE TITLE
touchpad navigation in flatpak wayland version

### ISSUE THREAD

**Issue by DaRandomCube** [flathub/com.brave.Browser#584]
tried running with `--enable-features=TouchpadOverscrollHistoryNavigation` option and made sure that it uses wayland, still no success

system : arch linux
DE : plasma 6 with wayland

**Comment by Malom-ctrl** [comment]
I ran into the same problem in the past. Here is how i solved it :

- Go to ~/.var/app/com.brave.Browser/config
- Create a file named brave-flags.conf if it doesn't already exist.
- In brave-flags.conf, add the following line :
`features+=TouchpadOverscrollHistoryNavigation`

For some reason the command line flag doesn't work but this does.

Let me know if it did the trick for you.

**Comment by DaRandomCube** [comment]
found another way which i don't remember
closing
