### ISSUE TITLE
chrome-flags.conf not working

### ISSUE THREAD

**Issue by alosarjos** [flathub/com.brave.Browser#59]
Hi there!

I'm trying to run Brave using Ozone/Wayland.

If I understood correctly the cobalt settings, I can pass flags to brave by setting the file:

`~/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser/chrome-flags.conf`

with this content:

`--enable-features=UseOzonePlatform --ozone-platform=wayland`

That should be enough, right? It's not picking them for me. I'm checking `brave://version/` to see if the flags are passed

**Comment by rany2** [comment]
Should be `~/.var/app/com.brave.Browser/config/chrome-flags.conf`.

**Comment by refi64** [comment]
It's worth noting that as of #55/#56 the *preferred* file name is brave-flags.conf (which is something I should have mentioned in the PR, oops!). *That being said*, the old name does still work; your flags will automatically be migrated to the new name, and the old file will contain a comment describing the change.

**Comment by rany2** [comment]
Wow, that's pretty cool. Nice. I probably should have inferred that from `MigrateFlagsFile` :smile:

**Comment by alosarjos** [comment]
Hmmm, do we know if there is any issue with wayland on these regard?

With the said config flags on the first post the `brave://version` is showing 

`/app/brave/brave --enable-features=UseOzonePlatform --ozone-platform=wayland` so it looks like it's picking it, but the window is actually running on Xwayland

Running it with `flatpak run com.brave.Browser --enable-features=UseOzonePlatform --ozone-platform=wayland` is actually working well

**Comment by refi64** [comment]
Hmm there shouldn't be, could you drop the full contents of your flags file here?

**Comment by rany2** [comment]
@refi64 Could it be that it is sending `-enable-features=UseOzonePlatform --ozone-platform=wayland` as a single argument?   
@alosarjos I don't know what you're doing but maybe you should have the `brave-flags.conf` file look something like:
```
-enable-features=UseOzonePlatform
--ozone-platform=wayland
```

instead of:
```
-enable-features=UseOzonePlatform --ozone-platform=wayland
```

**Comment by alosarjos** [comment]
> @refi64 Could it be that it is sending `--enable-features=UseOzonePlatform --ozone-platform=wayland` as a single argument?
> @alosarjos I don't know what you're doing but maybe you should have the `brave-flags.conf` file look something like:
> 
> ```
> --enable-features=UseOzonePlatform
> --ozone-platform=wayland
> ```
> 
> instead of:
> 
> ```
> --enable-features=UseOzonePlatform --ozone-platform=wayland
> ```

This is it. I put all the flags on one line each and it's working nice. Not sure if could be considered an issue, the flags file is the same I was using for the AUR brave-bin package and was working nice there.

**Comment by rany2** [comment]
@refi64 I guess you might want to have Cobalt delimit arguments by both space and newline.

**Comment by refi64** [comment]
Ah yup that's it, I was viewing that on a phone so the line wrapped, and I thought they were on separate lines.

**Comment by flipflop133** [comment]
What's the config file for brave nightly then? I tried brave-nightly-flags.conf and it didn't worked.

**Comment by rany2** [comment]
@flipflop133 The flags file is something added by packagers. I guess you used the official package for nightly and those don't have support for the flags files.

**Comment by francoism90** [comment]
Sorry for the old topic bump, but this work for me:
```bash
$ cat /home/<user>/.var/app/com.brave.Browser/config/brave-flags.conf
--ignore-gpu-blocklist
--enable-zero-cop
--enable-gpu-rasterization
--enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,VaapiVideoDecodeLinuxGL,VaapiVideoEncoder,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
```
