### ISSUE TITLE
Fatal error when I open Brave

### ISSUE THREAD

**Issue by zachvlat** [flathub/com.brave.Browser#595]
I get this image
![image](https://github.com/flathub/com.brave.Browser/assets/28532979/ec98f752-e987-4468-927a-975372aa1520)

$ flatpak run com.brave.Browser

(process:3): Gtk-WARNING **: 16:03:04.619: Locale not supported by C library.
        Using the fallback 'C' locale.

CPU: 4x AMD Ryzen 3 2200G with Radeon Vega Graphics
Memory: 8.27 GB (used: 4.01 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    IDs: D=67df V=1002 SD=0b31 SV=1002
    Driver: amdgpu
OS: Arch Linux 6.8.8-arch1-1 (linux)

**Comment by rany2** [comment]
Follow the instructions that the dialog box shows you.

**Comment by zachvlat** [comment]
Unfortunately it didn't work for me...

**Comment by rany2** [comment]
Are you using the linux-hardened kernel on Arch?

**Comment by zachvlat** [comment]
> Are you using the linux-hardened kernel on Arch?

No just the stock
