### ISSUE TITLE
Not available on Flathub?

### ISSUE THREAD

**Issue by da2x** [flathub/com.brave.Browser#6]
What’s the status on this page? The [Brave page on Flathub](https://flathub.org/apps/details/com.brave.Browser) returns a 404.

**Comment by Chemrat** [comment]
It's in `flathub-beta` repo, you need to add it first via `flatpak remote-add`

**Comment by rany2** [comment]
```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flathub install flathub-beta com.brave.Browser
```
