### ISSUE TITLE
Worse font rendering compared to native

### ISSUE THREAD

**Issue by alosarjos** [flathub/com.brave.Browser#61]
Is this a known issue or something that can be fixed?

Left: Flatpak
Right: Native

![Captura de pantalla de 2021-07-29 18-06-45](https://user-images.githubusercontent.com/29999427/127527091-e30ad50c-287a-49bd-8b48-3cfba52d5b8d.png)

PD: Both are with the default font settings, haven't changed anything

**Comment by rany2** [comment]
IIRC Flatpak doesn't pull the host system's fontconfig, only the host's fonts.  https://github.com/flatpak/flatpak/issues/1563
