### ISSUE TITLE
GPU rendering working in Chrome but not Brave

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/com.brave.Browser#66]
Brave flatpak 
![image](https://user-images.githubusercontent.com/14835120/131504319-f491cc96-b9a5-4602-81cd-2c241ba1bb1e.png)

Chrome flatpak
![image](https://user-images.githubusercontent.com/14835120/131504370-bfed98c9-db44-4912-bb3b-cc51a21b78b1.png)

**Comment by alosarjos** [comment]
Seems to be something on your side. Just installed the flatpak and it's working

![Captura de pantalla de 2021-09-02 20-55-39](https://user-images.githubusercontent.com/29999427/131900813-8f838c86-fffb-412a-941d-df645e231d1f.png)

**Comment by alvarlagerlof** [comment]
Okay

**Comment by nonetrix** [comment]
I had to install Flatseal and enable it there it is not enable by default for some reason

**Comment by rany2** [comment]
@nonetrix Not sure how that's possible, I've already set --devices=all. What option did you flick in Flatseal?

**Comment by alvarlagerlof** [comment]
I get most things enabled by default using the default permissions. Tried just now pressing reset on flatseal.

**Comment by nonetrix** [comment]
I just installed Brave from discover on KDE neon and picked the Flatpak version, noticed it was slow and CSS backdrop effects are broken, went to about://gpu notice GPU acceleration is not working. I open flatseal to see that GPU acceleration is turned off

Many thing where off most everything was sensible defaults expect for GPU acceleration being turned off

I am not able to use my computer right now so I'll edit this comment most likely to include ```cat ~/.local/share/flatpak/overrides/com.brave.Browser```

**Comment by nonetrix** [comment]
> @nonetrix Not sure how that's possible, I've already set --devices=all. What option did you turn on in Flatseal?
> 
> Edit: it would be better if you just send me the output of `cat ~/.local/share/flatpak/overrides/com.brave.Browser`


```
[Context]
devices=dri
```
