### ISSUE TITLE
Missing PWA shortcuts fucntionality

### ISSUE THREAD

**Issue by Chemrat** [flathub/com.brave.Browser#7]
Chromium-based browsers are capable of installing shortcuts/`.desktop` files for PWAs. On Linux they go into `~/.local/share/applications`.

This doesn't seem to work with Brave from flatpak, even if I allow access to `~/.local/share/applications`.

Sample PWA app: https://twitter.com/, to "install" click on Plus in the address bar next to the Brave icon.

**Comment by rany2** [comment]
I'll fix this in the next release of Brave by using Flextop

**Comment by rany2** [comment]
Fixed in the latest version. Currently still building

**Comment by Chemrat** [comment]
Thanks for the fix. `.desktop` files are now being created.
However, flextop generated `.desktop` files make me hit flatpak/flatpak#3044, i.e.:
```
$ flatpak 'run' '--command=/app/brave/brave-browser' 'com.brave.Browser' '--profile-directory=Default' '--app-id=jgeocpdicgmkeemopbanhokmhcgcflmi'
[8:8:1211/013757.835225:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/brave/chrome-sandbox is owned by root and has mode 4755.
```
Specifically because of the addition of `--command=/app/brave/brave-browse` which flextop does. If I remove this from `.destkop` file it works again. I'm not sure what causes this, if this belongs here or should I open a bug in flextop repo?

**Comment by refi64** [comment]
This needs CHROME_WRAPPER set to the absolute path to the wrapper script to
work (aware this is not really documented yet for flextop, but it is for
recent zypak releases and is required for chrome://restart to work
properly).

**Comment by rany2** [comment]
Thanks! I guess this is solved.
