### ISSUE TITLE
Kerberos doesn't work in flatpak

### ISSUE THREAD

**Issue by jkonecny12** [flathub/com.brave.Browser#74]
Hello,

I would like to use Brave browser from Flatpak, unfortunately I can't switch because my work is a heavy user of kerberos tickets and it seems that the Brave doesn't support this if launched from Flatpak.

Steps to reproduce:
1. Enable your kerberos ticket.
2. `flatpak run com.brave.Browser --auth-server-whitelist=.example.com` 
3. Go to site and try to login by kerberos.

If you need some debug data, feel free to ask.

**Comment by nanonyme** [comment]
Something like https://github.com/flathub/org.mozilla.firefox.BaseApp/commit/f8ef0b766cc23be262f5349947c0f2d3c4193b56 should probably be ported into this repo

**Comment by rany2** [comment]
Thanks, I think it should be fixed now.

**Comment by jkonecny12** [comment]
Unfortunately, doesn't work for me. At least I'm not able to log-in to sites with kerb SSO and I don't see anything in `brave://policy/`. Could someone else please also test this if it's on my side only?

**Comment by rany2** [comment]
@jkonecny12 How are you deploying your Chrome policy?

**Comment by jkonecny12** [comment]
IIRC using the command line arguments should be enough to make the kerberos ticket to work. It's basically replacing requirement to have the policy. My wild guess is that the flatpak don't have access to the local kerberos ticket but truth is that I don't know how the ticket is read by the browsers... :(

**Comment by rany2** [comment]
@jkonecny12 I think it could work with https://github.com/flathub/com.brave.Browser/commit/4a20222eb327a2fce51a7034443f1937f5136448

**Comment by jkonecny12** [comment]
I guess it should help, but I can't still set the policy. I don't know why. I'll try to experiment with this a bit to find the reason.

**Comment by TheEvilSkeleton** [comment]
@jkonecny12 any update?

**Comment by jkonecny12** [comment]
Hi, wasn't able to get to that. I have to install Brave to toolbx, find the way there and then try to apply that for Flatpak version.

I'll try to do that soon but not sure when I get to that.

**Comment by jkonecny12** [comment]
Hi, I was finally able to test it. So I did the test of flatpak and brave installed in the [toolbx](https://github.com/containers/toolbox).

The Toolbx:
- running `brave-browser-stable` -> kerberos ticket is not used
- running `brave-browser-stable --auth-server-whitelist=.example.com` -> kerberos ticket is working

- creating policy file at `/etc/brave/policies/managed/example.json` with content
```
{
		"AuthServerAllowlist": ".example.com"
}
```
and running  `brave-browser-stable` -> kerberos ticket is working

In flatpak:
- running `flatpak run com.brave.Browser --auth-server-whitelist=.example.com` -> kerberos ticket is working
- running `flatpak run com.brave.Browser` -> kerberos ticket is not working
- running `flatpak run com.brave.Browser` with the policy above created on /etc/ on host -> kerberos ticket is not working


So it's partially working. The kerberos ticket works for the command line argument but not for the policy created on the system.

**Comment by rany2** [comment]
Policies created on /etc host don't work with Flatpak because it couldn't access host as a security measure.  

You could always add your `--auth-server-whitelist=.example.com` line to `~/.var/app/com.brave.Browser/config/brave-flags.conf` until we add support for policy extensions like we have on {Ungoogled,} Chromium.

**Comment by rany2** [comment]
Here is the issue for that: https://github.com/flathub/com.brave.Browser/issues/103

**Comment by jkonecny12** [comment]
Thanks a lot for all your help. I finally can use Brave as my default!

**Comment by Zlopez** [comment]
Just for anyone who will struggle like me with this. The recent update of Brave changed the flag name from `--auth-server-whitelist` to `--auth-server-allowlist`.

Thank to political correctness for this one :-D
