### ISSUE TITLE
Can't move bookmarks to bookmark folders.

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/com.brave.Browser#82]
It ends up switching desktop one step to the left instead.

**Comment by rany2** [comment]
As a temporary solution, you could always cut the bookmark and paste it into the bookmark folder. However I am not sure if this is an issue specific to your setup and isn't a Flatpak only issue.

**Comment by alvarlagerlof** [comment]
Not having any issues on MacOS so it's at least a Linux issue.

**Comment by alvarlagerlof** [comment]
Not having any issues on MacOS so it's at least a Linux issue.

**Comment by TheCultLeader666** [comment]
Works fine on Fedora Silverblue

**Comment by alvarlagerlof** [comment]
Yes this now seems to be fixed!
