### ISSUE TITLE
Gamepads not detected

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/com.brave.Browser#84]
https://gamepad-tester.com/

I have confirmed that this works in Flatpak in general, as it works in Firefox and Jstest-gtk

**Comment by TheEvilSkeleton** [comment]
@alvarlagerlof sorry for the late reply. Can you try the workaround [here](https://github.com/flathub/com.microsoft.Edge#game-controllers-not-working)?

**Comment by alvarlagerlof** [comment]
> @alvarlagerlof sorry for the late reply. Can you try the workaround [here](https://github.com/flathub/com.microsoft.Edge#game-controllers-not-working) and see whether it works or not?

Worked immediately.

**Comment by alvarlagerlof** [comment]
For some reason, the fix linked above no longer seems to be needed.
