### ISSUE TITLE
GPU acceleration not working on Wayland

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/com.brave.Browser#85]
![image](https://user-images.githubusercontent.com/14835120/141858615-79e7d645-45bd-486d-9a36-0c18331d9ee6.png)

**Comment by TheEvilSkeleton** [comment]
Are you using the necessary flags to run with GPU acceleration?

**Comment by alvarlagerlof** [comment]
@TheEvilSkeleton As far as I know yes. Everything looks like chrome in brave on xorg. My issue here is that the default setup in Chrome on wayland comes with more capabilities.

**Comment by TheEvilSkeleton** [comment]
You'll have to pass through `--enable-features=VaapiVideoDecoder` and `--use-gl=egl`, per https://wiki.archlinux.org/title/Chromium#Hardware_video_acceleration. If you want it to run native Wayland, then it's `--use-gl=egl --enable-features=VaapiVideoDecoder,UseOzonePlatform --ozone-platform=wayland`.

**Comment by alvarlagerlof** [comment]
> You'll have to pass through `--enable-features=VaapiVideoDecoder` and `--use-gl=egl`, per https://wiki.archlinux.org/title/Chromium#Hardware_video_acceleration. If you want it to run native Wayland, then it's `--use-gl=egl --enable-features=VaapiVideoDecoder,UseOzonePlatform --ozone-platform=wayland`.

What I am asking is why these are not default like Chrome, the base feature set works on both X11 and wayland.

**Comment by refi64** [comment]
You need to flip on `brave://flags/#ignore-gpu-blocklist`. Your Chrome install's GPU acceleration flags are *not* the default setup, however (Vulkan in particular is not enabled by default yet), they were either changed and you forgot (check `chrome://flags`) or you're part of an A/B trial being tested by Chrome. Either way though, this isn't something we'd be controlling in the Flatpak's end.
