### ISSUE TITLE
Brave does not store cookies between restarts

### ISSUE THREAD

**Issue by rivi** [flathub/com.brave.Browser#9]
Cookies are lost when the browser is restarted. It seems the problem was already mentioned in https://github.com/flathub/com.brave.Browser/issues/1#issuecomment-716215811 and https://github.com/flathub/com.brave.Browser/issues/1#issuecomment-728990737.

I'm using Fedora Silverblue 33 if it makes any difference.

**Comment by Zlopez** [comment]
I can confirm this is happening, it's quite annoying to log in to everything each time. I even needed to fill 2-factor authentication again, so it seems that the browser is recognized as different browser by various sites (GitHub for instance) after each restart.

**Comment by rany2** [comment]
Probably related to https://github.com/flathub/com.google.Chrome/issues/9
