### ISSUE TITLE
Video rubberbands after a while

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/com.brave.Browser#97]
Rubber-banding is probably not the right word, but the longer I play, the more frames seem to jump back to a previous one then snap back.

**Comment by rany2** [comment]
I'm closing this issue because NVIDIA+Wayland is very recent (just yesterday) and the bugs affect other Flatpak apps as well. I'll give Brave/Chrome/runtimes/etc (whatever the source of the issue is) some time to fix it. 

Reopen if this issue is not NVIDIA+Wayland only.
